export default {
  // 定数
  DAY_OF_WEEK_JA: ['日', '月', '火', '水', '木', '金', '土'],
  GARBAGE_LIST: ['燃やせるごみ', 'プラスチック製容器梱包', '燃やせないゴミ', '古紙・紙製容器梱包'],

  UPDATE_AUTH_STATUS: 'UPDATE_AUTH_STATUS',
  UPDATE_USER_PROFILE: 'UPDATE_USER_PROFILE',
  FETCH_SCHOOL_LIST: 'FETCH_SCHOOL_LIST',
  CHECK_USER_TOKEN: 'CHECK_USER_TOKEN',
  BEGIN_LOADER: 'BEGIN_LOADER',
  FINISH_LOADER: 'FINISH_LOADER',
  BEGIN_UPLOAD_SCHEDULE: 'BEGIN_UPLOAD_SCHEDULE',
  FINISH_UPLOAD_SCHEDULE: 'FINISH_UPLOAD_SCHEDULE',
  FETCH_SCHEDULES: 'FETCH_SCHEDULES',
  FETCH_ANSWERED_LOG: 'FETCH_ANSWERED_LOG',
  FETCH_UNANSWERED_LOG: 'FETCH_UNANSWERED_LOG',
  FETCH_MONTHLY_TIMELINE: 'FETCH_MONTHLY_TIMELINE',
  FETCH_SEPARATION_DATA: 'FETCH_SEPARATION_DATA',

  // OAuthのクライアントID
  OAUTH_CLIENT_ID: '630972852282-qorrq9qhp77kqp39pk25m66pqe2imv2i.apps.googleusercontent.com',
  // GoogleマップのクライアントID
  MAP_CLIENT_TOKEN: 'AIzaSyCoGjWW556lfx7mW_tXDIMYe1GYOsaRSiY'
};
